#!/bin/bash

# This file contains variables supplementing gsec_common for build target
# "parallel".  It should be included via "source", not run directly.

# Currently it is empty, as "parallel" was used as the starting point.
