#!/bin/bash

# This file contains variables supplementing gsec_common for build targets
# "release" and "debug" (which was the original "crazymerge").  It should be
# included via "source", not run directly.

KLEE_BRANCH="crazymerge1.0.0"
USE_STP_NEW=1
