#!/bin/bash

# This file contains variables supplementing gsec_common for build target
# "parallel".  It should be included via "source", not run directly.

# This is intentionally blank. Currently, gsec_common already provides the
# right parameters for this build.
