#!/bin/bash

# This file contains variables supplementing gsec_common for build target
# "parallel-e".  It should be included via "source", not run directly.

KLEE_BRANCH="parallel-rc-thesis-fakepadding"
OPENSSL_BRANCH="playback_101ef"
USE_STP_NEW=0
